services:
  # Backend Service (Node.js/Express + Socket.io)
  - type: web
    name: code-editor-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run server:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_ORIGIN
        fromService:
          type: web
          name: code-editor-frontend
          property: url

  # Frontend Service (React)
  - type: web
    name: code-editor-frontend
    env: static
    plan: free
    buildCommand: npm ci && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_BACKEND_URL
        fromService:
          type: web
          name: code-editor-backend
          property: url
